### ISSUE TITLE
Implement per-character views of missing fragments

### ISSUE THREAD

**Issue by AaronMT** [sjlu/calcified-fragments#3]
Bungie just released an updated API which allows for one to view fragments per character for a given account (PSN/Xbox). It would be awesome if http://destinycalcifiedfragments.com could be updated to make use of this new API.

**Comment by sjlu** [comment]
Yup, working on it as we speak.

**Comment by sjlu** [comment]
So at the moment, it looks like Bungie has not officially released the endpoint to be viewable by the public just yet.

It can be viewed by the logged in user at the moment (e.g. DIM)

I'll keep this thread posted when there's more information. I have completed the preliminary work for it though, just a matter of that endpoint activating.

e936c037150d50292f6c42a5518c4d8faf162d49

**Comment by weswhite** [comment]
Yeah, so I had to go look at which character had which on bungies page. Let me know if  there is anything I could help work on. Looking to play around with the api.

**Comment by sjlu** [comment]
No worries, it's a pretty straight forward change, it's just that they're
implementing a data privacy setting for all their users. Their "advisors"
endpoint depends on that change. No word just yet when it'll be activated.

**Comment by sjlu** [comment]
This has finally been done!
